using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TackTimeManager.Persistence.Common
{
    public class TableName
    {
        public static string ACTION = "ACTION.DBF";
        public static string ACTMPLT = "ACTMPLT.DBF";
        public static string ADDLBTMP = "ADDLBTMP.DBF";
        public static string ADDRBOOK = "ADDRBOOK.DBF";
        public static string ADJLABEL = "ADJLABEL.DBF";
        public static string ALTCUR = "ALTCUR.DBF";
        public static string AUDITMP = "AUDITMP.DBF";
        public static string AUDPNERR = "AUDPNERR.DBF";
        public static string AVAIL = "AVAIL.DBF";
        public static string BEM = "BEM.DBF";
        public static string BILLING = "BILLING.DBF";
        public static string BILLTMP = "BILLTMP.DBF";
        public static string BOM = "BOM.DBF";
        public static string BOMTEMP = "BOMTEMP.DBF";
        public static string BPLATES = "BPLATES.DBF";
        public static string CALENDAR = "CALENDAR.DBF";
        public static string CARTPAGES = "CARTPAGES.DBF";
        public static string CCARD = "CCARD.DBF";
        public static string char0821 = "char0821.dbf";
        public static string CHARTACC = "CHARTACC.DBF";
        public static string CLOSEDAT = "CLOSEDAT.DBF";
        public static string CONSOL = "CONSOL.DBF";
        public static string CONTACTS = "CONTACTS.DBF";
        public static string CONTDET = "CONTDET.DBF";
        public static string COSTSALE = "COSTSALE.DBF";
        public static string CUSTPRICE = "CUSTPRICE.DBF";
        public static string CYCTMP = "CYCTMP.DBF";
        public static string DATASTRU = "DATASTRU.DBF";
        public static string DIVISION = "DIVISION.DBF";
        public static string ecn = "ecn.dbf";
        public static string EDICUSPOHD = "EDICUSPOHD.DBF";
        public static string EDICUSPOIT = "EDICUSPOIT.DBF";
        public static string EDIGRPHDR = "EDIGRPHDR.DBF";
        public static string EDIINTHDR = "EDIINTHDR.DBF";
        public static string EDIINVHD = "EDIINVHD.DBF";
        public static string EDIINVIT = "EDIINVIT.DBF";
        public static string EDIPOACKHD = "EDIPOACKHD.DBF";
        public static string EDIPOACKIT = "EDIPOACKIT.DBF";
        public static string EDIRULES = "EDIRULES.DBF";
        public static string EDISETTING = "EDISETTING.DBF";
        public static string EDITRANHDR = "EDITRANHDR.DBF";
        public static string EFFL = "EFFL.DBF";
        public static string employee = "employee.dbf";
        public static string EMPTIMESH = "EMPTIMESH.DBF";
        public static string ERROR = "ERROR.DBF";
        public static string FIFOTMP = "FIFOTMP.DBF";
        public static string FLINKS = "FLINKS.DBF";
        public static string FORMSETS = "FORMSETS.DBF";
        public static string FoxUser = "FoxUser.dbf";
        public static string GRPH = "GRPH.dbf";
        public static string IMPTMPLT = "IMPTMPLT.DBF";
        public static string INSPCRIT = "INSPCRIT.DBF";
        public static string INSPECT = "INSPECT.DBF";
        public static string INSPTPLT = "INSPTPLT.DBF";
        public static string INVOICE = "INVOICE.DBF";
        public static string LABORCODE = "LABORCODE.DBF";
        public static string Lists = "Lists.dbf";
        public static string MAKECONS = "MAKECONS.DBF";
        public static string MOVEMENT = "MOVEMENT.DBF";
        public static string MRP2CONS = "MRP2CONS.DBF";
        public static string MRPBOM = "MRPBOM.DBF";
        public static string MRPERROR = "MRPERROR.DBF";
        public static string MrpPart = "MrpPart.DBF";
        public static string MRPPO = "MRPPO.DBF";
        public static string MRPSO = "MRPSO.DBF";
        public static string MRPSTOCK = "MRPSTOCK.DBF";
        public static string MRPTMP = "MRPTMP.DBF";
        public static string MSG = "MSG.DBF";
        public static string PARTMAST = "PARTMAST.DBF";
        public static string partmast20210722 = "partmast20210722.DBF";
        public static string partmast20220215 = "partmast20220215.DBF";
        public static string PARTPRICE = "PARTPRICE.DBF";
        public static string PARTVEND = "PARTVEND.DBF";
        public static string PIH = "PIH.DBF";
        public static string POPMSG = "POPMSG.DBF";
        public static string PPVTMP = "PPVTMP.DBF";
        public static string PRGLTMP = "PRGLTMP.DBF";
        public static string PRTRNTMP = "PRTRNTMP.DBF";
        public static string PURCHASE = "PURCHASE.DBF";
        public static string QbAccess = "QbAccess.DBF";
        public static string QBCLASS = "QBCLASS.DBF";
        public static string QbPartsDbf = "QbPartsDbf.dbf";
        public static string QUERIES = "QUERIES.DBF";
        public static string quote = "quote.dbf";
        public static string RECEIVE = "RECEIVE.DBF";
        public static string request = "request.dbf";
        public static string ROUTETMPLTS = "ROUTETMPLTS.DBF";
        public static string routing = "routing.dbf";
        public static string RTMPLATE = "RTMPLATE.DBF";
        public static string SALES = "SALES.DBF";
        public static string SANAL = "SANAL.DBF";
        public static string SHIPITEM = "SHIPITEM.DBF";
        public static string SHIPLOG = "SHIPLOG.DBF";
        public static string SHIPMENT = "SHIPMENT.DBF";
        public static string SNLOT = "SNLOT.DBF";
        public static string SNLOTDET = "SNLOTDET.DBF";
        public static string STAXENT = "STAXENT.DBF";
        public static string STOCKREC = "STOCKREC.DBF";
        public static string STOCKTRA = "STOCKTRA.DBF";
        public static string SULF = "SULF.DBF";
        public static string SYSKEY = "SYSKEY.DBF";
        public static string TASKS = "TASKS.DBF";
        public static string TEMPECN = "TEMPECN.DBF";
        public static string TEMPEST = "TEMPEST.DBF";
        public static string TEMPSHRT = "TEMPSHRT.DBF";
        public static string TERMCOND = "TERMCOND.DBF";
        public static string TRAIL = "TRAIL.DBF";
        public static string TRANDETAIL = "TRANDETAIL.DBF";
        public static string TRANSACT = "TRANSACT.DBF";
        public static string TRANSLATION = "TRANSLATION.DBF";
        public static string USERSETS = "USERSETS.DBF";
        public static string wp = "wp.dbf";
        public static string wspercnt = "wspercnt.dbf";
    }
}
